import shlex
import time
import logging
from ssh_client import RemoteSession

logger = logging.getLogger("eda_mcp.eldo_client")

class EldoClient:
    """
    High-level client for managing and executing Mentor Graphics/Siemens Eldo simulations
    over a RemoteSession SSH transport.
    """
    def initialize(self, work_dir: str = "~/Desktop/eldo") -> str:
        """
        Navigates to work_dir (default: ~/Desktop/eldo) and sets working directory for Eldo.
        """
        self.session.connect()
        target_dir = work_dir.strip() if work_dir and work_dir.strip() else "~/Desktop/eldo"
        self.workdir = target_dir
        
        safe_dir = f"$HOME{target_dir[1:]}" if target_dir.startswith("~") else shlex.quote(target_dir)
        cmd = f"cd {safe_dir}"
        exit_code, stdout, stderr = self.session.execute_command(cmd)
        
        if exit_code != 0:
            return f"Failed to initialize Eldo working directory at {target_dir} (Exit code {exit_code}): {stdout}"

        return f"Eldo session initialized in {target_dir}."

    def run_script(self, script_path: str = "", work_dir: str = "") -> str:
        """
        Runs Eldo simulation on a batch script or netlist file, redirects output to mcp_run.log,
        and reads the log content via read_file.
        """
        self.session.connect()
        target_dir = (work_dir.strip() if work_dir and work_dir.strip() else None) or self.workdir or "~/Desktop/eldo"
        safe_dir = f"$HOME{target_dir[1:]}" if target_dir.startswith("~") else shlex.quote(target_dir)
        self.session.execute_command(f"cd {safe_dir}")

        if not script_path.strip():
            return "Error: 'command' argument specifying script/netlist path is required for action='run_script'."

        log_file = "mcp_run.log"

        # Clear & touch log file before running script
        self.session.execute_command(f"rm -f {log_file} && touch {log_file}")

        # Execute Eldo simulation script piping stdout & stderr to mcp_run.log
        quoted_script = shlex.quote(script_path.strip())
        run_cmd = f"eldo {quoted_script} >& {log_file}"
        exit_code, stdout, stderr = self.session.execute_command(run_cmd)

        # Read the log content using read_file
        try:
            log_content = self.session.read_file(log_file)
        except Exception as e:
            log_content = f"Error reading {log_file}: {str(e)}"

        output = []
        output.append(f"[Eldo Batch Script Run]: eldo {quoted_script}")
        output.append(f"Exit Status: {exit_code}")
        if stdout.strip():
            output.append(f"\n--- STDOUT ---\n{stdout}")
        if stderr.strip():
            output.append(f"\n--- STDERR / ERROUT ---\n{stderr}")
        if log_content.strip():
            output.append(f"\n--- LOG CONTENT ({log_file}) ---\n{log_content}")

        return "\n".join(output)

    def run_interactive(self, command: str = "", work_dir: str = "") -> str:
        """
        Executes interactive Eldo command.
        """
        self.session.connect()
        target_dir = (work_dir.strip() if work_dir and work_dir.strip() else None) or self.workdir or "~/Desktop/eldo"
        safe_dir = f"$HOME{target_dir[1:]}" if target_dir.startswith("~") else shlex.quote(target_dir)
        self.session.execute_command(f"cd {safe_dir}")

        if not command.strip():
            return "Eldo interactive execution placeholder. Pass an Eldo command to execute."

        exit_code, stdout, stderr = self.session.execute_command(command)
        output = []
        output.append(f"Exit Status: {exit_code}")
        if stdout.strip():
            output.append(f"\n--- STDOUT ---\n{stdout}")
        if stderr.strip():
            output.append(f"\n--- STDERR ---\n{stderr}")
        return "\n".join(output)

    def read_extract(self, work_dir: str = "") -> str:
        """
        Reads the .extract measurement file generated by the most recent Eldo simulation run.
        """
        self.session.connect()
        target_dir = (work_dir.strip() if work_dir and work_dir.strip() else None) or self.workdir or "~/Desktop/eldo"
        safe_dir = f"$HOME{target_dir[1:]}" if target_dir.startswith("~") else shlex.quote(target_dir)
        self.session.execute_command(f"cd {safe_dir}")

        # Auto-detect the most recently created .extract file
        find_extract_cmd = "ls -t *.extract 2>/dev/null | head -n 1"
        exit_code, stdout, _ = self.session.execute_command(find_extract_cmd)
        extract_file = stdout.strip()

        if not extract_file:
            return f"No .extract measurement file found in working directory ({target_dir}). Ensure netlist ran successfully and contains .EXTRACT or .MEASURE directives."

        try:
            content = self.session.read_file(extract_file)
            output = []
            output.append(f"[Eldo Extracted Measurement File]: {extract_file}")
            output.append(f"\n--- CONTENT ({extract_file}) ---\n{content}")
            return "\n".join(output)
        except Exception as e:
            return f"Error reading extracted measurement file '{extract_file}': {str(e)}"
